### ISSUE TITLE
Visual design needed

### ISSUE THREAD

**Issue by lpil** [slime-lang/slime-lang.github.io#2]
I can sort of do CSS, but I can't do design at all. Could anyone help here?

**Comment by Benderwan** [comment]
Could help if you wish, tell me what to do :)

**Comment by lpil** [comment]
Welll it'd be nice is this site looked better. What would you like to contribute?

**Comment by Benderwan** [comment]
I can make a few designs for your website, I saw it on designer network and thought I could help you reach a broader audience. What would you wish me to start with ?

**Comment by lpil** [comment]
I'm unsure. Perhaps @doomspork might have suggestions.

I envision a site that plays a role similar to the Jade reference. http://jade-lang.com/reference/

I also rather like the way that the Slim site introduces you to the language. slim-lang.com

**Comment by doomspork** [comment]
Hi @Benderwan, thanks for offering your assistance!

I was thinking something simple that highlights the features of Slime, how to use it, and provides a language reference.  Both [Jade](http://jade-lang.com) and [Slim](http://slim-lang.com) are good examples as @lpil pointed out.

As for the layout or design, I don't have any real strong feelings at the moment.  If you want to mock up some examples I'd be glad to look at them and brainstorm with you.  I'm sure @lpil could provide feedback as well.  However works best for you.

Thanks again!

**Comment by lpil** [comment]
! I forgot to say thanks. How rude. Thank you for helping :)

**Comment by Benderwan** [comment]
So we can start by saying that you would like the language to be introduced with an exemple (both Slim and Jade do so) ?
Anyway, I'm pleased to help you :)

**Comment by doomspork** [comment]
@Benderwan I think that's a good idea.  It gives you a taste of the language and you can decide if it's something you want to work with.

**Comment by Benderwan** [comment]
Okay, I'll see if I can find examples around and will submit them to you so I could have a better understanding of all your needs.

**Comment by Benderwan** [comment]
Hi,
I quickly looked for a few template engine websites and I could split them in 2 categories in term of organization, all of them actually have an example code as an introduction to show how easy it is to use their language, which I think is a very good idea for a templating engine. You would then have those who embed the whole docs in one page, might be good if there isn't that much functions / reference so you can avoid switching pages and have to wait for each page to load, but this might become hard to manage when you've got a lot of docs where splitting into pages would be a better idea, users wouldn't get lost. Here are a few examples:
http://handlebarsjs.com/ & http://beebole.com/pure/ (One-page docs)
http://jinja.pocoo.org/ & http://www.mitchellbosecke.com/pebble/home (Split)
Bonus :stuck_out_tongue_closed_eyes:  http://unslider.com/ (Nice solution there: everything in one request but the content is still split -> no waiting time and still usable).

By the way I would be glad if you pointed out things you like / dislike from those websites :smile:
Have a nice day guys.

**Comment by doomspork** [comment]
@Benderwan thanks for pulling these examples together.  I think I prefer the split approach but like the simplicity of all of them.  

I like the Slim and Handlebar sites because they use color and are "fun".  I don't much care for Pebble's site, it feels bland and their example is dwarfed by the paragraphs of text elsewhere on the page.

**Comment by lpil** [comment]
I like the split approach, and I also prefer the sites that have a page for each section of the documentation, rather than one long page.

**Comment by Benderwan** [comment]
Okay I'll do a few prototypes :smile: 
Note also that I will be away from monday, 15th february to friday 26th as I am on a business trip to Australia. Anyway I'll work on this as much as i can :)

**Comment by lpil** [comment]
No rush :)

Thank you!

**Comment by doomspork** [comment]
There's no rush so take your time.  We appreciate your interest in helping @Benderwan :+1:
