### ISSUE TITLE
Add possibility to try Slime online

### ISSUE THREAD

**Issue by hedgesky** [slime-lang/slime-lang.github.io#6]
I always thought that it's awesome when you could play with a language without installing it to your system. Several languages have sandboxes for this ([coffeescript.org ("Try" tab)](http://coffeescript.org/), [tryruby.org](http://tryruby.org/), plenty of supported languages on [repl.it](http://repl.it/)).
I thought it would be useful to have something similar on Slime site. Especially for those who are unfamiliar to Slim/Slime syntax.
That's why I've built a tool for that: [Slime converter](https://slime-converter.herokuapp.com/). It converts Slime templates to EEx (and also prettifies them). At first I thought about just implementing an API so we could use it as a backend for static [slime-lang.com](slime-lang.com), but then just couldn't stop 😄 . Here is [the converter repo](https://github.com/hedgesky/slime_converter_app).

I suggest adding a "Try" tab to slime-lang.com and some JS to connect it with converter API.
@doomspork, @lpil, what do you think?

**Comment by lpil** [comment]
As this would involve executing unverified code we'd need to be very careful about security here.

**Comment by hedgesky** [comment]
If you are concerned about executing 3rd party scripts: there would be no scripts loaded from that app. JS for initiating POST requests with template to convert would be stored at this repo.

Or maybe you are concerned about the fact of transferring template?

**Comment by lpil** [comment]
Any arbitrary Elixir code will be run by the compiling process so it opens
up the server to bring hijacked.

**Comment by hedgesky** [comment]
Yeah, I thought about it. That's why the service only converts Slime to EEx without compiling it to HTML: there is no user provided code execution.

**Comment by lpil** [comment]
I'm not sure how that would be useful to a user. What's the use case?

**Comment by hedgesky** [comment]
A person who know how EEx templates work, but who isn't familiar with Slime thing may find out what given Slime template is equal to.
It's a translator from a language which a user don't know to a language which user know.
